import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  IsNumber,
  IsDateString,
  Min,
  IsBoolean,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { AssignmentStatus } from '@prisma/client';
import { Type } from 'class-transformer';

export class CreateAssignmentDto {
  @ApiPropertyOptional({ description: 'Batch ID if this is a batch-wide assignment' })
  @IsOptional()
  @IsString()
  batchId?: string;

  @ApiPropertyOptional({ description: 'Student Profile ID for personalized assignment' })
  @IsOptional()
  @IsString()
  studentProfileId?: string;

  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  topicId!: string;

  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  title!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ example: '2026-08-10T23:59:59Z' })
  @IsDateString()
  dueDate!: string;
}

export class SubmitAssignmentDto {
  @ApiProperty({ description: 'URL to the submitted document (e.g. S3)' })
  @IsString()
  @IsNotEmpty()
  submissionUrl!: string;
}

export class GradeAssignmentDto {
  @ApiProperty({ example: 8.5 })
  @IsNumber()
  @Min(0)
  gradedMarks!: number;
}

export class QueryAssignmentsDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  batchId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  studentProfileId?: string;

  @ApiPropertyOptional({ enum: AssignmentStatus })
  @IsOptional()
  @IsEnum(AssignmentStatus)
  status?: AssignmentStatus;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  isAutoGenerated?: boolean;

  @ApiPropertyOptional({ default: 1 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  page?: number = 1;

  @ApiPropertyOptional({ default: 20 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  limit?: number = 20;
}
