'use client';

import { useEffect, useRef, useState } from 'react';
import { FileText, FileCheck, FileClock, FileWarning, Search, UploadCloud, CheckCircle2, X, ExternalLink, Loader2 } from 'lucide-react';
import { useAssignments, useSubmitAssignment, useAssignmentSubmissionUrl } from '@/hooks/useApi';

interface Assignment {
  id: string;
  title: string;
  description?: string | null;
  dueDate: string;
  status: 'PENDING' | 'SUBMITTED' | 'LATE_SUBMITTED' | 'GRADED' | 'MISSED';
  topic?: { name: string };
  gradedMarks?: number | null;
  isAutoGenerated: boolean;
}

type Tab = 'pending' | 'submitted' | 'completed';
const TAB_STATUSES: Record<Tab, Assignment['status'][]> = {
  pending: ['PENDING'],
  submitted: ['SUBMITTED', 'LATE_SUBMITTED'],
  completed: ['GRADED'],
};

function ViewSubmissionButton({ assignmentId }: { assignmentId: string }) {
  const [armed, setArmed] = useState(false);
  const { data, isFetching } = useAssignmentSubmissionUrl(armed ? assignmentId : null);

  // Open the signed URL exactly once when it arrives — never inside the render body
  // because that re-triggers on every re-render and opens multiple tabs.
  useEffect(() => {
    if (data?.url) {
      window.open(data.url, '_blank', 'noopener,noreferrer');
      setArmed(false);
    }
  }, [data?.url]);

  return (
    <button
      onClick={() => setArmed(true)}
      disabled={isFetching}
      className="px-3 py-1.5 bg-slate-50 text-slate-600 hover:bg-slate-100 text-[11px] font-bold rounded-lg transition-colors border border-slate-200 flex items-center gap-1.5"
    >
      {isFetching ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <ExternalLink className="w-3.5 h-3.5" />} View Submission
    </button>
  );
}

export function StudentAssignments() {
  const [activeTab, setActiveTab] = useState<Tab>('pending');
  const [searchQuery, setSearchQuery] = useState('');
  const [submitModalOpen, setSubmitModalOpen] = useState<Assignment | null>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { data: assignmentsResp, isPending } = useAssignments();
  const submitAssignment = useSubmitAssignment();
  const assignments: Assignment[] = assignmentsResp?.data ?? [];

  const counts = {
    pending: assignments.filter((a) => TAB_STATUSES.pending.includes(a.status)).length,
    submitted: assignments.filter((a) => TAB_STATUSES.submitted.includes(a.status)).length,
    completed: assignments.filter((a) => TAB_STATUSES.completed.includes(a.status)).length,
  };
  const total = counts.pending + counts.submitted + counts.completed;
  const progress = total > 0 ? Math.round(((counts.submitted + counts.completed) / total) * 100) : 0;

  const filteredAssignments = assignments.filter((a) => {
    const matchesTab = TAB_STATUSES[activeTab].includes(a.status);
    const q = searchQuery.toLowerCase();
    const matchesSearch = a.title.toLowerCase().includes(q) || (a.topic?.name ?? '').toLowerCase().includes(q);
    return matchesTab && matchesSearch;
  });

  async function handleSubmit() {
    if (!submitModalOpen || !selectedFile) return;
    await submitAssignment.mutateAsync({ assignmentId: submitModalOpen.id, file: selectedFile });
    setSubmitModalOpen(null);
    setSelectedFile(null);
  }

  function dueLabel(a: Assignment) {
    if (a.status === 'GRADED') return a.gradedMarks != null ? `Graded: ${a.gradedMarks}` : 'Graded';
    if (a.status === 'SUBMITTED' || a.status === 'LATE_SUBMITTED') return a.status === 'LATE_SUBMITTED' ? 'Submitted late' : 'Submitted';
    const days = Math.ceil((new Date(a.dueDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
    if (days < 0) return 'Overdue';
    if (days === 0) return 'Due today';
    return `Due in ${days}d`;
  }

  return (
    <div className="p-5 animate-fadein h-full">
      <div className="card shadow-sm border border-slate-100 rounded-2xl w-full h-full p-6 lg:p-8 flex flex-col relative overflow-hidden">

        {/* Header & Progress */}
        <div className="flex flex-col md:flex-row md:justify-between md:items-center mb-8 gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center">
              <FileText className="w-5 h-5 text-emerald-600" />
            </div>
            <div>
              <h2 className="text-[19px] font-bold text-slate-800">Assignments</h2>
              <p className="text-[12px] text-slate-500">Track and submit your coursework.</p>
            </div>
          </div>

          <div className="flex items-center gap-4 bg-slate-50 px-4 py-2.5 rounded-xl border border-slate-100">
            <div className="flex-1">
              <div className="flex justify-between text-[11px] font-bold text-slate-600 mb-1.5">
                <span>Weekly Progress</span>
                <span className="text-emerald-600">{progress}%</span>
              </div>
              <div className="w-32 bg-slate-200 rounded-full h-1.5">
                <div className="bg-emerald-500 h-1.5 rounded-full transition-all duration-1000" style={{ width: `${progress}%` }} />
              </div>
            </div>
          </div>
        </div>

        {/* Controls: Tabs & Search */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-100 mb-6 gap-4">
          <div className="flex items-center gap-8 overflow-x-auto no-scrollbar">
            {[
              { id: 'pending' as const, label: `Pending (${counts.pending})` },
              { id: 'submitted' as const, label: `Submitted (${counts.submitted})` },
              { id: 'completed' as const, label: `Completed (${counts.completed})` },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`pb-3 text-[13.5px] font-bold transition-all relative whitespace-nowrap ${
                  activeTab === tab.id ? 'text-slate-800' : 'text-slate-400 hover:text-slate-600'
                }`}
              >
                {tab.label}
                {activeTab === tab.id && (
                  <div className="absolute bottom-[-1px] left-0 right-0 h-[2px] bg-emerald-500 rounded-t-full animate-fadein" />
                )}
              </button>
            ))}
          </div>

          <div className="relative pb-2 sm:pb-3 w-full sm:w-64">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none pb-2 sm:pb-3">
              <Search className="w-4 h-4 text-slate-400" />
            </div>
            <input
              type="text"
              placeholder="Search assignments..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-[13px] focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all placeholder:text-slate-400"
            />
          </div>
        </div>

        {/* List */}
        <div className="space-y-3 mb-6 flex-1 overflow-y-auto pr-2 custom-scrollbar">
          {isPending ? (
            <div className="space-y-3">{[1, 2, 3].map((i) => <div key={i} className="h-16 bg-slate-100 rounded-xl animate-pulse" />)}</div>
          ) : filteredAssignments.length > 0 ? (
            filteredAssignments.map((item) => {
              const Icon = item.status === 'GRADED' ? FileCheck : item.status === 'PENDING' ? FileClock : FileWarning;
              return (
                <div key={item.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-xl hover:bg-slate-50 transition-colors border border-slate-100 group gap-4">
                  <div className="flex items-start sm:items-center gap-4">
                    <div className="w-11 h-11 rounded-xl bg-emerald-50 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-5 h-5 text-emerald-600" />
                    </div>
                    <div>
                      <p className="text-[14px] font-bold text-slate-800 group-hover:text-emerald-700 transition-colors">{item.title}</p>
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-[11px] font-semibold text-slate-500 bg-slate-100 px-2 py-0.5 rounded">{item.topic?.name ?? 'General'}</span>
                        {item.isAutoGenerated && <span className="text-[10px] font-bold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded">Auto-generated</span>}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between sm:justify-end gap-6 sm:w-1/3">
                    <div className="text-left sm:text-right">
                      <p className="text-[11px] text-slate-400 mb-0.5">{item.status === 'PENDING' ? 'Due in' : 'Status'}</p>
                      <p className="text-[13px] font-bold text-slate-700">{dueLabel(item)}</p>
                    </div>
                    {item.status === 'PENDING' ? (
                      <button
                        onClick={() => { setSubmitModalOpen(item); setSelectedFile(null); }}
                        className="px-4 py-1.5 bg-emerald-50 text-emerald-600 hover:bg-emerald-500 hover:text-white text-[12px] font-bold rounded-lg transition-colors border border-emerald-100 hover:border-emerald-500"
                      >
                        Submit
                      </button>
                    ) : (
                      <ViewSubmissionButton assignmentId={item.id} />
                    )}
                  </div>
                </div>
              );
            })
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-slate-400 py-10">
              <FileCheck className="w-12 h-12 mb-3 opacity-20" />
              <p className="text-[14px] font-medium text-slate-500">No assignments found.</p>
              {searchQuery && <p className="text-[12px] mt-1">Try adjusting your search query.</p>}
            </div>
          )}
        </div>

        {/* Submit Modal — real file upload */}
        {submitModalOpen && (
          <div className="absolute inset-0 z-50 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center animate-fadein p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 relative animate-slide-up">
              <button
                onClick={() => !submitAssignment.isPending && setSubmitModalOpen(null)}
                className="absolute top-4 right-4 p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="w-12 h-12 bg-emerald-100 rounded-xl flex items-center justify-center mb-4">
                <UploadCloud className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-[18px] font-bold text-slate-800 mb-1">Submit Assignment</h3>
              <p className="text-[13px] text-slate-500 mb-6 font-medium">{submitModalOpen.title}</p>

              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,.doc,.docx,image/*"
                className="hidden"
                onChange={(e) => setSelectedFile(e.target.files?.[0] ?? null)}
              />
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="w-full border-2 border-dashed border-slate-200 rounded-xl p-8 text-center hover:border-emerald-400 hover:bg-emerald-50/50 transition-colors cursor-pointer mb-6 group"
              >
                <FileText className="w-8 h-8 text-slate-300 mx-auto mb-3 group-hover:text-emerald-400 transition-colors" />
                <p className="text-[13px] font-bold text-slate-700">{selectedFile ? selectedFile.name : 'Click to browse or select a file'}</p>
                <p className="text-[11px] text-slate-400 mt-1">PDF, DOCX, or Images up to 10MB</p>
              </button>

              <button
                onClick={handleSubmit}
                disabled={submitAssignment.isPending || !selectedFile}
                className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[13px] rounded-xl transition-all disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {submitAssignment.isPending ? (
                  <span className="flex items-center gap-2">
                    <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> Uploading...
                  </span>
                ) : (
                  <> <CheckCircle2 className="w-4 h-4" /> Submit Work</>
                )}
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
