'use client';

import { useState } from 'react';
import { useAssignments } from '@/hooks/useApi';
import { Search, Filter, ClipboardList, Zap } from 'lucide-react';

export function AssignmentsList() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  
  const { data: assignmentsData, isLoading } = useAssignments({
    status: status || undefined,
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-semibold text-navy-900">Assignments</h2>
          <p className="text-sm text-navy-500">Track batch assignments and AI-generated remedial tasks.</p>
        </div>
      </div>

      <div className="card p-4 flex flex-col sm:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-navy-400" />
          <input
            type="text"
            placeholder="Search assignments..."
            className="input pl-10"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="relative sm:w-48">
          <Filter className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-navy-400" />
          <select
            className="input pl-10 appearance-none bg-transparent"
            value={status}
            onChange={(e) => setStatus(e.target.value)}
          >
            <option value="">All Statuses</option>
            <option value="PENDING">Pending</option>
            <option value="SUBMITTED">Submitted</option>
            <option value="GRADED">Graded</option>
          </select>
        </div>
      </div>

      <div className="card p-0 overflow-hidden">
        {isLoading ? (
          <div className="p-8 text-center text-navy-500">Loading assignments...</div>
        ) : assignmentsData?.data?.length === 0 ? (
          <div className="p-12 text-center">
            <ClipboardList className="w-12 h-12 text-navy-300 mx-auto mb-3" />
            <p className="text-navy-900 font-medium mb-1">No assignments found.</p>
            <p className="text-navy-500 text-sm">Create an assignment or run the auto-generator.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-navy-50 text-navy-700 border-b border-border">
                <tr>
                  <th className="px-6 py-4 font-medium">Title</th>
                  <th className="px-6 py-4 font-medium">Target</th>
                  <th className="px-6 py-4 font-medium">Topic</th>
                  <th className="px-6 py-4 font-medium">Due Date</th>
                  <th className="px-6 py-4 font-medium">Status</th>
                  <th className="px-6 py-4 font-medium text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {assignmentsData?.data.map((assignment: any) => (
                  <tr key={assignment.id} className="hover:bg-navy-50/50 transition-colors">
                    <td className="px-6 py-4 font-medium text-navy-900 flex items-center gap-2">
                      {assignment.isAutoGenerated && <span title="Auto-generated"><Zap className="w-4 h-4 text-warning" /></span>}
                      {assignment.title}
                    </td>
                    <td className="px-6 py-4 text-navy-700">
                      {assignment.studentProfile ? `Student: ${assignment.studentProfile.user?.name}` : 
                       assignment.batch ? `Batch: ${assignment.batch.name}` : 'Unknown'}
                    </td>
                    <td className="px-6 py-4 text-navy-700">{assignment.topic?.name || '—'}</td>
                    <td className="px-6 py-4 text-navy-700">
                      {new Date(assignment.dueDate).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4">
                      <span className={`chip-${
                        assignment.status === 'PENDING' ? 'warning' : 
                        assignment.status === 'GRADED' ? 'success' : 'navy'
                      }`}>
                        {assignment.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button className="text-teal-600 hover:text-teal-800 font-medium text-xs">
                        View Details
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
