import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { StorageService } from '../infrastructure/storage/storage.service';
import { AuditAction, UserRole, AssignmentStatus } from '@prisma/client';
import { AuthenticatedUser } from '../auth/auth.types';
import {
  CreateAssignmentDto,
  SubmitAssignmentDto,
  GradeAssignmentDto,
  QueryAssignmentsDto,
} from './dto/assignment.dto';
import { getTeacherBatchIds } from '../shared/teacher-scope';

/**
 * The only rows a STUDENT may ever read.
 *
 * SECURITY: the previous form was `OR: [{studentProfileId: me}, {batchId: myBatch}]`.
 * Because the "assign to a class" flow writes ONE ROW PER STUDENT — each row
 * carrying BOTH batchId and studentProfileId — that second clause matched every
 * classmate's row, exposing their names, submission status and marks to anyone
 * in the batch. The batch clause is now restricted to rows that have no student
 * attached at all (`studentProfileId: null`, the schema's "batch-wide" shape),
 * which by construction cannot carry another student's identity or grade.
 */
export function studentVisibilityFilter(studentProfileId: string, batchId: string | null) {
  const own = { studentProfileId };
  if (!batchId) return own;
  return { OR: [own, { batchId, studentProfileId: null }] };
}

/** True when this student is allowed to read the given assignment row. */
export function studentMayAccessAssignment(
  assignment: { studentProfileId: string | null; batchId: string | null },
  student: { id: string; batchId: string | null } | null,
): boolean {
  if (!student) return false;
  if (assignment.studentProfileId) return assignment.studentProfileId === student.id;
  return !!assignment.batchId && assignment.batchId === student.batchId;
}

@Injectable()
export class AssignmentsService {
  private readonly logger = new Logger(AssignmentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly storage: StorageService,
  ) {}

  // ── F-01: Create / Auto-Generate Assignment ──────────────────────────────

  async createAssignment(instituteId: string, dto: CreateAssignmentDto, actor: AuthenticatedUser, isAutoGenerated = false) {
    if (actor.role === UserRole.STUDENT) {
      throw new ForbiddenException('Students cannot create assignments.');
    }

    if (!dto.batchId && !dto.studentProfileId) {
      throw new BadRequestException('Must provide either batchId or studentProfileId');
    }

    // Cross-tenant write guard: a batch/student ID from another institute must
    // never be usable here just because the caller is authenticated somewhere.
    if (dto.batchId) {
      const batch = await this.prisma.batch.findUnique({ where: { id: dto.batchId } });
      if (!batch || batch.instituteId !== instituteId) {
        throw new BadRequestException('Batch does not belong to this institute.');
      }
    }
    if (dto.studentProfileId) {
      const student = await this.prisma.studentProfile.findUnique({
        where: { id: dto.studentProfileId },
        include: { user: { select: { instituteId: true } } },
      });
      if (!student || student.user.instituteId !== instituteId) {
        throw new BadRequestException('Student does not belong to this institute.');
      }
    }

    const assignment = await this.prisma.assignment.create({
      data: {
        batchId: dto.batchId,
        studentProfileId: dto.studentProfileId,
        topicId: dto.topicId,
        title: dto.title,
        description: dto.description,
        dueDate: new Date(dto.dueDate),
        isAutoGenerated,
        createdByUserId: actor.id,
      },
    });

    await this.writeAudit(instituteId, actor.id, AuditAction.CREATE, 'assignments', assignment.id, null, { title: assignment.title });

    return assignment;
  }

  // ── Auto-Assignment Trigger (Example for external services/cron to call) ─

  async triggerAutoAssignmentsForWeakTopics(instituteId: string, actor: AuthenticatedUser) {
    // Find mastery scores below 50%
    const weakTopics = await this.prisma.masteryScore.findMany({
      where: {
        studentProfile: { user: { instituteId } },
        masteryValue: { lt: 0.5 },
      },
      include: {
        studentProfile: true,
        topic: true,
      },
      take: 50, // Process in batches
    });

    const created = [];
    for (const record of weakTopics) {
      // Check if there is already a pending auto-assignment for this student+topic
      const existing = await this.prisma.assignment.findFirst({
        where: {
          studentProfileId: record.studentProfileId,
          topicId: record.topicId,
          status: AssignmentStatus.PENDING,
          isAutoGenerated: true,
        }
      });

      if (!existing) {
        const dto: CreateAssignmentDto = {
          studentProfileId: record.studentProfileId,
          topicId: record.topicId,
          title: `Remedial: ${record.topic.name}`,
          description: 'Auto-generated assignment based on recent exam performance.',
          // Due in 7 days
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        };

        const assignment = await this.createAssignment(instituteId, dto, actor, true);
        created.push(assignment);
      }
    }

    return { message: `Auto-generated ${created.length} assignments for weak topics.` };
  }

  // ── Query Assignments ────────────────────────────────────────────────────

  async findAll(instituteId: string, query: QueryAssignmentsDto, actor: AuthenticatedUser) {
    const page = query.page ?? 1;
    const limit = query.limit ?? 20;
    const skip = (page - 1) * limit;

    // Assignment has no direct instituteId — it's batch-wide or student-specific,
    // so tenant scoping has to go through whichever relation is set. Without this,
    // any authenticated ADMIN/TEACHER could list every institute's assignments.
    const and: any[] = [
      { OR: [{ batch: { instituteId } }, { studentProfile: { user: { instituteId } } }] },
    ];

    if (actor.role === UserRole.STUDENT) {
      const student = await this.prisma.studentProfile.findUnique({ where: { userId: actor.id } });
      if (!student) throw new ForbiddenException('Student profile not found');

      and.push(studentVisibilityFilter(student.id, student.batchId));
    } else {
      // Teachers only see assignments for their own batches (batch-wide or
      // individual, since a personalized Assignment still belongs to a
      // student within one of the teacher's batches) — ADMIN/FOUNDER keep
      // institute-wide visibility, unaffected by this branch.
      const teacherBatchIds = await getTeacherBatchIds(this.prisma, actor);
      if (teacherBatchIds !== null) {
        and.push({ OR: [{ batchId: { in: teacherBatchIds } }, { studentProfile: { batchId: { in: teacherBatchIds } } }] });
      }
    }

    if (query.batchId) and.push({ batchId: query.batchId });
    if (query.studentProfileId) and.push({ studentProfileId: query.studentProfileId });
    if (query.status) and.push({ status: query.status });
    if (query.isAutoGenerated !== undefined) and.push({ isAutoGenerated: query.isAutoGenerated });

    const where: any = { AND: and };

    const [assignments, total] = await Promise.all([
      this.prisma.assignment.findMany({
        where,
        include: {
          topic: { select: { name: true } },
          studentProfile: { select: { user: { select: { name: true } } } },
          batch: { select: { name: true } },
        },
        skip,
        take: limit,
        orderBy: { dueDate: 'asc' },
      }),
      this.prisma.assignment.count({ where }),
    ]);

    return {
      data: assignments,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  // ── Submit Assignment ────────────────────────────────────────────────────

  // Accepts a real uploaded file (multipart) OR a plain submissionUrl string
  // (kept for API-compat / non-browser callers) — never both. The file, when
  // present, is uploaded for real via StorageService under a tenant-scoped
  // key; submissionUrl stores that key, not a public URL (07-SECURITY-
  // SPECIFICATION.md — files are never served from an unsigned path). See
  // getSubmissionDownloadUrl() for how a key becomes a fresh signed link.
  async submitAssignment(
    instituteId: string,
    assignmentId: string,
    dto: SubmitAssignmentDto | undefined,
    actor: AuthenticatedUser,
    file?: { buffer: Buffer; originalname: string; mimetype: string },
  ) {
    if (actor.role !== UserRole.STUDENT) throw new ForbiddenException('Only students can submit assignments');
    if (!file && !dto?.submissionUrl) throw new BadRequestException('A file or submissionUrl is required');

    const assignment = await this.getAssignmentWithTenantCheck(assignmentId, instituteId);

    const student = await this.prisma.studentProfile.findUnique({ where: { userId: actor.id } });

    if (!studentMayAccessAssignment(assignment, student)) {
      throw new ForbiddenException('Not your assignment');
    }

    let submissionUrl = dto?.submissionUrl;
    if (file) {
      const safeName = file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_');
      const key = this.storage.buildKey(instituteId, 'assignments', assignmentId, `${Date.now()}_${safeName}`);
      await this.storage.upload(key, file.buffer, file.mimetype);
      submissionUrl = key;
    }

    const status = new Date() > assignment.dueDate ? AssignmentStatus.LATE_SUBMITTED : AssignmentStatus.SUBMITTED;

    return this.prisma.assignment.update({
      where: { id: assignmentId },
      data: {
        submissionUrl,
        submittedAt: new Date(),
        status,
      },
    });
  }

  // Own-record (STUDENT) or batch/institute-scoped (TEACHER/ADMIN/FOUNDER)
  // read of a submission's file as a fresh, time-limited signed URL — the
  // stored submissionUrl is a storage key, never directly openable.
  async getSubmissionDownloadUrl(instituteId: string, assignmentId: string, actor: AuthenticatedUser): Promise<{ url: string | null }> {
    const assignment = await this.getAssignmentWithTenantCheck(assignmentId, instituteId);
    if (!assignment.submissionUrl) return { url: null };

    if (actor.role === UserRole.STUDENT) {
      const student = await this.prisma.studentProfile.findUnique({ where: { userId: actor.id } });
      // Same rule as the list query: a row belonging to a named student is
      // readable only by that student. Previously any batch member could pull a
      // signed URL for a classmate's uploaded answer file.
      if (!studentMayAccessAssignment(assignment, student)) {
        throw new ForbiddenException('Not your assignment');
      }
    }

    const url = await this.storage.getSignedDownloadUrl(assignment.submissionUrl);
    return { url };
  }

  // ── Grade Assignment ─────────────────────────────────────────────────────

  async gradeAssignment(instituteId: string, assignmentId: string, dto: GradeAssignmentDto, actor: AuthenticatedUser) {
    if (actor.role === UserRole.STUDENT) throw new ForbiddenException('Students cannot grade');

    await this.getAssignmentWithTenantCheck(assignmentId, instituteId);

    return this.prisma.assignment.update({
      where: { id: assignmentId },
      data: {
        gradedMarks: dto.gradedMarks,
        gradedByUserId: actor.id,
        gradedAt: new Date(),
        status: AssignmentStatus.GRADED,
      },
    });
  }

  private async getAssignmentWithTenantCheck(assignmentId: string, instituteId: string) {
    const assignment = await this.prisma.assignment.findUnique({
      where: { id: assignmentId },
      include: {
        batch: { select: { instituteId: true } },
        studentProfile: { select: { user: { select: { instituteId: true } } } },
      },
    });
    if (!assignment) throw new NotFoundException('Assignment not found');

    const assignmentInstituteId = assignment.batch?.instituteId ?? assignment.studentProfile?.user.instituteId;
    if (assignmentInstituteId !== instituteId) {
      throw new ForbiddenException("You don't have access to this.");
    }
    return assignment;
  }

  private async writeAudit(instituteId: string, actorId: string, action: AuditAction, entity: string, entityId: string, oldValue: unknown, newValue: unknown) {
    try {
      await this.prisma.auditLog.create({
        data: { instituteId, actorId, action, entity, entityId, oldValue: oldValue as any, newValue: newValue as any },
      });
    } catch (err) {
      // Audit-log failures must never block the underlying mutation (08-ERROR-HANDLING.md);
      // still log so a persistent failure is visible rather than silently disappearing.
      this.logger.warn(`Failed to write audit log for ${entity}:${entityId}`, err as Error);
    }
  }
}
