packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  js-yaml: ^4.3.1
  '@angular-devkit/core>ajv': ^8.18.0
  'ajv-formats>ajv': ^8.18.0
  picomatch: ^4.0.4
  fast-uri: ^3.1.5
  '@typescript-eslint/typescript-estree>minimatch': ^9.0.7
  '@nestjs/cli>glob': ^10.5.0
  '@next/eslint-plugin-next>glob': ^10.5.0
  tmp: ^0.2.6
  webpack: ^5.104.1
  esbuild: ^0.25.0
  multer: ^2.2.0
  body-parser: ^1.20.6
  qs: ^6.15.2
  lodash: ^4.17.24
  uuid: ^11.1.1
  postcss: ^8.5.23
  nanoid: ^3.3.18
  vite: ^6.4.3
  file-type: ^21.3.2
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
