import asyncio
from types import SimpleNamespace
from unittest.mock import AsyncMock, patch

import pytest

from src.analytics.intervention_engine import evaluate_interventions


@pytest.fixture(autouse=True)
def _fixed_config():
    """threshold/max-weak-topics resolve through pydantic Settings, which
    needs real env vars this unit-test run has no reason to provide —
    patched at point of use, hermetic, matches test_mastery_engine.py."""
    with patch("src.analytics.intervention_engine.get_mastery_threshold", return_value=0.5), \
         patch("src.analytics.intervention_engine.get_max_weak_topics", return_value=1):
        yield


def make_student(batch_id="batch-1", institute_id="inst-1"):
    return SimpleNamespace(batchId=batch_id, user=SimpleNamespace(instituteId=institute_id))


def make_batch_teacher(teacher_user_id="teacher-1"):
    return SimpleNamespace(teacherProfile=SimpleNamespace(user=SimpleNamespace(id=teacher_user_id)))


def make_fake_db(
    student=None,
    batch_teacher="default",
    update_many_result=1,
    questions=None,
    topic_name="Rotational Motion",
):
    return SimpleNamespace(
        studentprofile=SimpleNamespace(find_unique=AsyncMock(return_value=student if student is not None else make_student())),
        batchteacher=SimpleNamespace(
            find_first=AsyncMock(return_value=make_batch_teacher() if batch_teacher == "default" else batch_teacher)
        ),
        masteryscore=SimpleNamespace(update_many=AsyncMock(return_value=update_many_result)),
        topic=SimpleNamespace(find_unique=AsyncMock(return_value=SimpleNamespace(name=topic_name))),
        question=SimpleNamespace(find_many=AsyncMock(return_value=questions if questions is not None else [])),
        assignment=SimpleNamespace(create=AsyncMock(return_value=SimpleNamespace(id="assign-1"))),
        intervention=SimpleNamespace(create=AsyncMock(return_value=SimpleNamespace(id="interv-1"))),
        notice=SimpleNamespace(create=AsyncMock(return_value=SimpleNamespace(id="notice-1"))),
        noticedelivery=SimpleNamespace(create=AsyncMock()),
        timetableslot=SimpleNamespace(create=AsyncMock()),  # present only so a stray call would be caught, never expected to be used
    )


@pytest.mark.asyncio
async def test_no_weak_topics_does_nothing():
    fake_db = make_fake_db()
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.9)])

    fake_db.studentprofile.find_unique.assert_not_awaited()
    fake_db.assignment.create.assert_not_awaited()


@pytest.mark.asyncio
async def test_weak_topic_below_threshold_creates_one_assignment_one_intervention_one_notification():
    fake_db = make_fake_db()
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.3)])

    fake_db.assignment.create.assert_awaited_once()
    fake_db.intervention.create.assert_awaited_once()
    fake_db.notice.create.assert_awaited_once()
    fake_db.noticedelivery.create.assert_awaited_once()

    assignment_data = fake_db.assignment.create.await_args.kwargs["data"]
    assert assignment_data["studentProfileId"] == "student-1"
    assert assignment_data["topicId"] == "topic-1"
    assert assignment_data["isAutoGenerated"] is True

    intervention_data = fake_db.intervention.create.await_args.kwargs["data"]
    assert intervention_data["type"] == "ASSIGNMENT"
    assert intervention_data["topicId"] == "topic-1"
    assert intervention_data["beforeMastery"] == 0.3


@pytest.mark.asyncio
async def test_never_creates_a_timetable_slot_or_any_extra_class():
    """Explicit, direct assertion of the hard requirement: no automatic extra
    class, ever — not just 'not implemented', actually never called."""
    fake_db = make_fake_db()
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)])

    fake_db.timetableslot.create.assert_not_awaited()
    # And no field on the created records smuggles in a schedule either.
    intervention_data = fake_db.intervention.create.await_args.kwargs["data"]
    assert intervention_data["type"] != "EXTRA_CLASS"
    assert "scheduledAt" not in intervention_data


@pytest.mark.asyncio
async def test_notice_is_targeted_at_the_relevant_teacher_with_a_distinct_type_marker():
    fake_db = make_fake_db(batch_teacher=make_batch_teacher(teacher_user_id="teacher-42"))
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.25)])

    notice_data = fake_db.notice.create.await_args.kwargs["data"]
    assert notice_data["createdByUserId"] == "teacher-42"
    assert notice_data["targetAudience"]["type"] == "MASTERY_INTERVENTION"
    assert notice_data["targetAudience"]["userIds"] == ["teacher-42"]
    assert notice_data["channels"] == ["IN_APP"]

    delivery_data = fake_db.noticedelivery.create.await_args.kwargs["data"]
    assert delivery_data["userId"] == "teacher-42"
    assert delivery_data["channel"] == "IN_APP"
    assert delivery_data["status"] == "SENT"


@pytest.mark.asyncio
async def test_only_the_single_most_severe_weak_topic_by_default():
    fake_db = make_fake_db()
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions(
            "student-1",
            [("topic-mild", "sub-1", 0.45), ("topic-severe", "sub-1", 0.1), ("topic-ok", "sub-1", 0.9)],
        )

    fake_db.assignment.create.assert_awaited_once()
    assert fake_db.assignment.create.await_args.kwargs["data"]["topicId"] == "topic-severe"


@pytest.mark.asyncio
async def test_max_weak_topics_configurable_above_one():
    fake_db = make_fake_db()
    with patch("src.analytics.intervention_engine.db", fake_db), \
         patch("src.analytics.intervention_engine.get_max_weak_topics", return_value=2):
        await evaluate_interventions(
            "student-1",
            [("topic-a", "sub-1", 0.1), ("topic-b", "sub-1", 0.2), ("topic-c", "sub-1", 0.4)],
        )

    assert fake_db.assignment.create.await_count == 2
    created_topics = {c.kwargs["data"]["topicId"] for c in fake_db.assignment.create.await_args_list}
    assert created_topics == {"topic-a", "topic-b"}


@pytest.mark.asyncio
async def test_reuses_existing_approved_questions_never_generates_new_content():
    questions = [
        SimpleNamespace(content="What causes rotational inertia?"),
        SimpleNamespace(content="Derive the formula for angular momentum."),
    ]
    fake_db = make_fake_db(questions=questions)
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)])

    where = fake_db.question.find_many.await_args.kwargs["where"]
    assert where == {"topicId": "topic-1", "isApproved": True, "deletedAt": None}
    description = fake_db.assignment.create.await_args.kwargs["data"]["description"]
    assert "What causes rotational inertia?" in description


@pytest.mark.asyncio
async def test_no_batch_assigned_skips_gracefully_without_error():
    fake_db = make_fake_db(student=SimpleNamespace(batchId=None, user=SimpleNamespace(instituteId="inst-1")))
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)])

    fake_db.assignment.create.assert_not_awaited()


@pytest.mark.asyncio
async def test_no_teacher_assigned_to_batch_subject_skips_without_burning_the_idempotency_claim():
    fake_db = make_fake_db(batch_teacher=None)
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)])

    fake_db.assignment.create.assert_not_awaited()
    # No teacher to attribute/notify -> the claim itself must never be spent.
    fake_db.masteryscore.update_many.assert_not_awaited()


@pytest.mark.asyncio
async def test_duplicate_event_finds_the_claim_already_taken_and_creates_nothing():
    """The direct idempotency case: update_many's WHERE (interventionTriggeredAt:
    None) no longer matches because a prior call already claimed it -> 0 rows
    updated -> this call must create nothing."""
    fake_db = make_fake_db(update_many_result=0)
    with patch("src.analytics.intervention_engine.db", fake_db):
        await evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)])

    fake_db.assignment.create.assert_not_awaited()
    fake_db.intervention.create.assert_not_awaited()
    fake_db.notice.create.assert_not_awaited()


@pytest.mark.asyncio
async def test_concurrent_duplicate_evaluation_events_produce_exactly_one_assignment():
    """Simulates two mastery-recalc jobs for the same student+topic racing
    each other (e.g. a BullMQ retry alongside the original attempt) against a
    single shared, stateful fake MasteryScore row — proving the atomicity is
    in the update_many WHERE clause itself, not in call ordering. Same
    Promise.allSettled-against-a-stateful-mock technique used for the
    NestJS-side concurrency tests in this codebase (assessments.service.spec.ts).
    """
    claim_state = {"claimed": False}

    async def racy_update_many(where, data):
        # Simulates Postgres row-level locking: only the first caller whose
        # WHERE still matches (interventionTriggeredAt IS NULL) succeeds.
        await asyncio.sleep(0)  # yield control, so both tasks interleave here
        if claim_state["claimed"]:
            return 0
        claim_state["claimed"] = True
        return 1

    fake_db = make_fake_db()
    fake_db.masteryscore.update_many = racy_update_many

    with patch("src.analytics.intervention_engine.db", fake_db):
        await asyncio.gather(
            evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)]),
            evaluate_interventions("student-1", [("topic-1", "sub-1", 0.2)]),
        )

    assert fake_db.assignment.create.await_count == 1
    assert fake_db.intervention.create.await_count == 1
    assert fake_db.notice.create.await_count == 1
