// ─── Domain: Batch Types ──────────────────────────────────────────────────────
import type { EntityLifecycleStatus, EntityOwnership } from '../academic-context.types';
import type { BatchTab } from '../academic-context.types';

export interface Batch {
  id:           string;
  label:        string;           // e.g., "11A", "12B"
  displayName:  string;           // e.g., "Batch 11A", "Class 12 - Section B"

  // ── Academic Context
  instituteId:  string;
  branchId:     string;
  sessionId:    string;
  classId:      string;
  examId:       string | null;
  subjectIds:   string[];         // Subjects taught in this batch

  // ── Capacity
  strength:     number;           // current enrolled students
  capacity:     number;           // max capacity

  // ── Performance (computed)
  avgScore:     number;
  trend:        'up' | 'down' | 'flat';
  pendingActions: number;         // AI-computed urgent action count

  // ── Teachers
  teachers:     BatchTeacher[];

  // ── Status
  status:       EntityLifecycleStatus;
  ownership:    EntityOwnership;
  createdAt:    string;
  updatedAt:    string;
}

export interface BatchTeacher {
  teacherId:    string;
  name:         string;
  subjectId:    string;
  subject:      string;
  initials:     string;
  isPrimary:    boolean;
  lastTaught:   string | null;
  topicsCovered: number;
}

export interface BatchStats {
  batchId:        string;
  totalStudents:  number;
  excellentCount: number;
  goodCount:      number;
  averageCount:   number;
  weakCount:      number;
  criticalCount:  number;
  avgScore:       number;
  attendancePct:  number;
  pendingDoubts:  number;
  pendingGrading: number;
  activeAssignments: number;
}

// ── Weak topic for a whole batch (computed from test analytics)
export interface BatchWeakTopic {
  topic:          string;
  chapter:        string;
  weakCount:      number;
  totalStudents:  number;
  avgScore:       number;
  weakPct:        number;
  trend:          'improving' | 'worsening' | 'stable';
  recommendedAction: 'extra-class' | 'revision-assignment' | 're-test' | null;
}

// ── AI Briefing per batch (generated by AI engine)
export interface BatchAIBriefing {
  batchId:    string;
  severity:   'good' | 'warning' | 'critical';
  headline:   string;
  reasoning:  string;
  actions:    BatchBriefingAction[];
  generatedAt: string;
}

export interface BatchBriefingAction {
  label:      string;
  type:       'extra-class' | 'assignment' | 'schedule-test' | 'notification';
  topicHint:  string | null;
  batchId:    string | null;
}

export interface CreateBatchInput {
  label:      string;
  classId:    string;
  examId?:    string;
  subjectIds: string[];
  capacity:   number;
  teacherAssignments: { teacherId: string; subjectId: string; isPrimary: boolean }[];
}

export type { BatchTab };
